# Generated by Django 5.0.4 on 2024-04-30 15:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.CharField(default=uuid.UUID('66260b23-98c8-46a8-b6a9-ba733c8c2101'), max_length=100, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BirthCertificate',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.basemodel')),
                ('district', models.CharField(blank=True, default='Kathmandu', max_length=100, null=True)),
                ('zone', models.CharField(blank=True, default='Bagmati', max_length=100, null=True)),
                ('municipal', models.CharField(blank=True, default='Tokha', max_length=100, null=True)),
                ('woda_no', models.PositiveIntegerField()),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('birth_place', models.CharField(choices=[('HOME', 'HOME'), ('HOSPITAL', 'HOSPITAL'), ('HEALTH POST', 'HEALTH POST'), ('OTHERS', 'OTHERS')], max_length=100)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHERS', 'OTHERS')], max_length=100)),
                ('birth_type', models.CharField(choices=[('SINGLE', 'SINGLE'), ('TWINS', 'TWINS'), ('TRIPLETS', 'TRIPLETS'), ('OTHERS', 'OTHERS')], max_length=100)),
                ('caste', models.CharField(max_length=100)),
                ('number', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
            bases=('app.basemodel',),
        ),
        migrations.CreateModel(
            name='ConfirmationPersonDetail',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.basemodel')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('relation', models.CharField(max_length=100)),
                ('citizenchip_no', models.CharField(max_length=200)),
                ('district', models.CharField(blank=True, default='Kathmandu', max_length=100, null=True)),
                ('municipal', models.CharField(blank=True, default='Tokha', max_length=100, null=True)),
                ('woda_no', models.PositiveIntegerField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.birthcertificate')),
            ],
            bases=('app.basemodel',),
        ),
        migrations.CreateModel(
            name='FathersModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.basemodel')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('citizenchip_no', models.CharField(max_length=200)),
                ('district', models.CharField(blank=True, default='Kathmandu', max_length=100, null=True)),
                ('municipal', models.CharField(blank=True, default='Tokha', max_length=100, null=True)),
                ('woda_no', models.PositiveIntegerField()),
                ('age', models.PositiveIntegerField()),
                ('occupation', models.CharField(max_length=200)),
                ('education', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=200)),
                ('religion', models.CharField(max_length=200)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.birthcertificate')),
            ],
            bases=('app.basemodel',),
        ),
        migrations.CreateModel(
            name='MothersModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.basemodel')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('citizenchip_no', models.CharField(max_length=200)),
                ('district', models.CharField(blank=True, default='Kathmandu', max_length=100, null=True)),
                ('municipal', models.CharField(blank=True, default='Tokha', max_length=100, null=True)),
                ('woda_no', models.PositiveIntegerField()),
                ('age', models.PositiveIntegerField()),
                ('occupation', models.CharField(max_length=200)),
                ('education', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=200)),
                ('religion', models.CharField(max_length=200)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.birthcertificate')),
            ],
            bases=('app.basemodel',),
        ),
    ]
