# Generated by Django 5.0.4 on 2024-04-30 15:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confirmationpersondetail',
            old_name='citizenchip_no',
            new_name='citizenship_no',
        ),
        migrations.RenameField(
            model_name='fathersmodel',
            old_name='citizenchip_no',
            new_name='citizenship_no',
        ),
        migrations.RenameField(
            model_name='mothersmodel',
            old_name='citizenchip_no',
            new_name='citizenship_no',
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='id',
            field=models.CharField(default=uuid.UUID('11f782a0-3526-4bd8-9309-a70ebd601d58'), max_length=100, primary_key=True, serialize=False),
        ),
    ]
